package com.wang.parking.member.parkingmember.mapper;

import com.wang.parking.member.parkingmember.entity.MonthCard;
import com.wang.parking.member.parkingmember.entity.MonthCardExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface MonthCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    long countByExample(MonthCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    int deleteByExample(MonthCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    int insert(MonthCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    int insertSelective(MonthCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    List<MonthCard> selectByExample(MonthCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    MonthCard selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    int updateByExampleSelective(@Param("record") MonthCard record, @Param("example") MonthCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    int updateByExample(@Param("record") MonthCard record, @Param("example") MonthCardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    int updateByPrimaryKeySelective(MonthCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table month_card
     *
     * @mbg.generated Mon May 09 11:32:31 CST 2022
     */
    int updateByPrimaryKey(MonthCard record);
}